project_name: solana-go
release:
  github:
    owner: dfuse-io
    name: solana-go
  name_template: '{{.Tag}}'
builds:
- goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - "386"
  targets:
  - linux_amd64
  - linux_386
  - darwin_amd64
  - windows_amd64
  - windows_386
  main: ./cmd/slnc
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  binary: slnc
  env:
  - CGO_ENABLED=0
  lang: go
archives:
- name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  replacements:
    "386": i386
    amd64: x86_64
    darwin: macOS
    linux: linux
    windows: windows
  format: tar.gz
  format_overrides:
  - goos: windows
    format: zip
  files:
  - licence*
  - LICENCE*
  - license*
  - LICENSE*
  - readme*
  - README*
  - changelog*
  - CHANGELOG*
nfpms:
- name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}'
  bindir: /usr/local/bin
snapcrafts:
- name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}'
snapshot:
  name_template: '{{ .Tag }}-next'
checksum:
  name_template: checksums.txt
changelog:
  filters:
    exclude:
    - '^docs:'
    - '^test:'
  sort: asc
dist: dist
signs:
- cmd: keybase
  args:
  - sign
  - --infile
  - $artifact
  - --binary
  - --outfile
  - $signature
  - --detached
  signature: ${artifact}.sig
  artifacts: checksum
env_files:
  github_token: ~/.config/goreleaser/github_token
brews:
- github:
    owner: dfuse-io
    name: homebrew-tap
  homepage: "https://dfuse.io/"
  description: "Cross-platform Solana command-line swiss-army-knife"
